apiVersion: v1
kind: Service
metadata:
  name: accessories-service
spec:
  type: ClusterIP
  ports:
  - name: "accessories-service"
    port: 8081
    targetPort: 8081
  selector:
    app: accessories-service

