apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mediator
  name: mediator
spec:
  ports:
  - name: "mediator"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: mediator
status:
  loadBalancer: {}
